### ISSUE TITLE
[role] Fix redirection triggered by dropdown in access create and update

### ISSUE THREAD

**Issue by isDipesh** [isDipesh/awecms#1]
Commit 54d9bd325ee7e0dbf1733e6abf8badaad45e59cc is broken.
(event handling for select box changes in roles module)

Selection of module and controller from dropdown in access creation doesn't redirect to correct location.

This is broken in create. Requires fix.

This is not implemented in update. Requires implementation.

**Comment by RohitRox** [comment]
fixed here 176e9f81a83b1a62eb792ff69bd8fa6c7aedcf59

**Comment by isDipesh** [comment]
You only fixed it for create. Update doesn't work.

**Comment by RohitRox** [comment]
implemented in update page in this commit baea7e6cec06b0a8d111c43a90c8d26692185478

**Comment by isDipesh** [comment]
Works perfect!
